var searchData=
[
  ['gap_0',['gap',['../md_docs_2AUDIT.html#autotoc_md43',1,'Authenticity gap'],['../md_docs_2AUDIT.html#autotoc_md79',1,'Confirmed macOS architecture gap']]],
  ['gaps_1',['Remaining gaps',['../md_docs_2distribution-hardening-evidence.html#autotoc_md325',1,'']]],
  ['gate_2',['6. Release inventory gate',['../md_docs_2TASKS.html#autotoc_md201',1,'']]],
  ['gate_20—_20final_20acceptance_20checklist_3',['Release gate — final acceptance checklist',['../md_docs_2TASKS.html#autotoc_md269',1,'']]],
  ['gate_20is_20keyed_20to_20the_20wrong_20repository_20identity_4',['High: Windows release cache gate is keyed to the wrong repository identity',['../md_docs_2AUDIT.html#autotoc_md76',1,'']]],
  ['gcc_20clang_5',['GCC / Clang',['../md_docs_2development__guide.html#autotoc_md280',1,'']]],
  ['getlogoimg_6',['getLogoImg',['../classcpp__proj_1_1App.html#ae76fa5c8a3e6830ca800777405c84b49',1,'cpp_proj::App']]],
  ['getting_20started_7',['Getting Started',['../md_docs_2getting__started.html',1,'Getting Started'],['../index.html#autotoc_md360',1,'Getting Started']]],
  ['getting_5fstarted_2emd_8',['getting_started.md',['../getting__started_8md.html',1,'']]],
  ['git_20tag_20reference_20integrity_9',['45. Git/tag/reference integrity',['../md_docs_2TASKS.html#autotoc_md263',1,'']]],
  ['github_10',['GitHub',['../md_docs_2development__guide.html#autotoc_md305',1,'']]],
  ['github_20actions_2011_20workflows_11',['8.2 GitHub Actions (11 workflows)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md147',1,'']]],
  ['github_20actions_20hardening_12',['30. GitHub Actions hardening',['../md_docs_2TASKS.html#autotoc_md241',1,'']]],
  ['github_20actions_20tips_13',['GitHub Actions tips',['../md_docs_2development__guide.html#autotoc_md290',1,'']]],
  ['github_20and_20gitlab_14',['3. One release manifest for GitHub and GitLab',['../md_docs_2TASKS.html#autotoc_md198',1,'']]],
  ['github_20copy_20gitlab_20copy_15',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md160',1,'']]],
  ['github_20gitlab_20copies_20into_20one_20repo_16',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md129',1,'']]],
  ['github_20release_20pipeline_17',['12. GitHub release pipeline',['../md_docs_2AUDIT.html#autotoc_md35',1,'']]],
  ['github_20release_20version_20resolution_20occurs_20too_20late_18',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['github_20validation_19',['v0.0.9 GitHub validation',['../md_docs_2AUDIT.html#autotoc_md66',1,'']]],
  ['github_20workflows_20release_20yml_20',['.github/workflows/release.yml',['../md_docs_2AUDIT.html#autotoc_md53',1,'']]],
  ['github_20workflows_20windows_20arm64_20package_20smoke_20yml_21',['.github/workflows/windows-arm64-package-smoke.yml',['../md_docs_2AUDIT.html#autotoc_md59',1,'']]],
  ['github_20workflows_20windows_20package_20smoke_20yml_22',['.github/workflows/windows-package-smoke.yml',['../md_docs_2AUDIT.html#autotoc_md58',1,'']]],
  ['gitlab_23',['GitLab',['../md_docs_2TASKS.html#autotoc_md198',1,'3. One release manifest for GitHub and GitLab'],['../md_docs_2development__guide.html#autotoc_md306',1,'GitLab']]],
  ['gitlab_20as_20is_24',['12.4 Carried over from GitLab as-is',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md164',1,'']]],
  ['gitlab_20ci_20yml_25',['.gitlab/.gitlab-ci.yml',['../md_docs_2AUDIT.html#autotoc_md54',1,'']]],
  ['gitlab_20copies_20into_20one_20repo_26',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md129',1,'']]],
  ['gitlab_20copy_27',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md160',1,'']]],
  ['gitlab_20gitlab_20ci_20yml_28',['.gitlab/.gitlab-ci.yml',['../md_docs_2AUDIT.html#autotoc_md54',1,'']]],
  ['gitlab_20parity_20and_20security_29',['31. GitLab parity and security',['../md_docs_2TASKS.html#autotoc_md242',1,'']]],
  ['gitlab_20pipeline_30',['8.4 GitLab pipeline',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md149',1,'']]],
  ['gitlab_20release_20pipeline_31',['13. GitLab release pipeline',['../md_docs_2AUDIT.html#autotoc_md38',1,'']]],
  ['gitlab_20tips_32',['GitLab tips',['../md_docs_2development__guide.html#autotoc_md292',1,'']]],
  ['google_20test_20manual_20install_20not_20recommended_20prefer_20vcpkg_33',['Google Test (manual install not recommended, prefer vcpkg)',['../md_docs_2install.html#autotoc_md338',1,'']]],
  ['governance_34',['governance',['../md_docs_2TASKS.html#autotoc_md243',1,'32. Repository governance'],['../md_docs_2TASKS.html#autotoc_md240',1,'P1 — CI/CD security and governance']]],
  ['graph_35',['2. Repository Lineage and Fork Graph',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md104',1,'']]],
  ['green_20yet_36',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md317',1,'']]],
  ['guide_37',['Guide',['../index.html#autotoc_md362',1,'Developer Guide'],['../md_docs_2development__guide.html',1,'Development Guide'],['../md_docs_2install.html',1,'Installation Guide']]],
  ['gz_20—_20keep_20harden_38',['Linux tar.gz — KEEP / HARDEN',['../md_docs_2AUDIT.html#autotoc_md29',1,'']]],
  ['gz_20distribution_39',['P0 — Linux DEB/RPM/tar.gz distribution',['../md_docs_2TASKS.html#autotoc_md216',1,'']]]
];
