var searchData=
[
  ['baseline_20before_20any_20edit_0',['PASS 0 — Reconnaissance (baseline, before any edit)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md310',1,'']]],
  ['baseline_20release_20contract_20live_20v0_200_209_1',['Baseline release contract (live, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md311',1,'']]],
  ['baselines_2',['P0 — Runtime compatibility and platform baselines',['../md_docs_2TASKS.html#autotoc_md221',1,'']]],
  ['basis_3',['Research basis',['../md_docs_2TASKS.html#autotoc_md273',1,'']]],
  ['be_20claimed_20green_20yet_4',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md317',1,'']]],
  ['before_20any_20edit_5',['PASS 0 — Reconnaissance (baseline, before any edit)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md310',1,'']]],
  ['before_20editing_6',['Findings (re-proven from this HEAD before editing)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md320',1,'']]],
  ['behavior_7',['34. Offline and restricted-network behavior',['../md_docs_2TASKS.html#autotoc_md247',1,'']]],
  ['benefits_20to_20compiling_20across_20all_20these_20compiler_20variants_8',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['best_20i686_20x86_5f64_20arm64_9',['11.2 Q: Are the architecture names the best? (i686, x86_64, arm64)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md157',1,'']]],
  ['between_20clang_20and_20llvm_20in_20the_20matrix_10',['11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'']]],
  ['binary_20cache_20contract_20adr_20006_202026_2009_2025_11',['PASS 4 — vcpkg binary-cache contract (ADR 006, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md319',1,'']]],
  ['binary_20hardening_20checks_12',['20. Binary-hardening checks',['../md_docs_2TASKS.html#autotoc_md223',1,'']]],
  ['binary_20policy_13',['9. Windows runtime and binary policy',['../md_docs_2TASKS.html#autotoc_md206',1,'']]],
  ['block_14',['Deferred (per issue §7, must not block)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md312',1,'']]],
  ['block_20only_15',['Windows .7z — REMOVE FROM PUBLISHING / KEEP DISABLED HISTORICAL BLOCK ONLY',['../md_docs_2AUDIT.html#autotoc_md21',1,'']]],
  ['blockers_16',['P0 — Release blockers',['../md_docs_2TASKS.html#autotoc_md195',1,'']]],
  ['boundaries_17',['44. Build isolation and trust boundaries',['../md_docs_2TASKS.html#autotoc_md262',1,'']]],
  ['budget_18',['16.4 Operator action: cache budget',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md185',1,'']]],
  ['bugs_20and_20observations_20found_20during_20inspection_19',['13.4 Bugs and observations found during inspection',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md171',1,'']]],
  ['bugs_20txt_20',['13.7 Residual follow-ups (carried over from &lt;span class=&quot;tt&quot;&gt;BUGS.txt&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md174',1,'']]],
  ['build_20inputs_21',['24. Deterministic build inputs',['../md_docs_2TASKS.html#autotoc_md231',1,'']]],
  ['build_20isolation_20and_20trust_20boundaries_22',['44. Build isolation and trust boundaries',['../md_docs_2TASKS.html#autotoc_md262',1,'']]],
  ['build_20system_23',['Build system',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md146',1,'8.1 Build system'],['../md_docs_2AUDIT.html#autotoc_md5',1,'Build system']]],
  ['build_20truth_20adr_20001_24',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['builds_25',['P1 — Reproducible builds',['../md_docs_2TASKS.html#autotoc_md230',1,'']]],
  ['bundle_26',['12. Real application bundle',['../md_docs_2TASKS.html#autotoc_md211',1,'']]],
  ['bundle_20—_20fix_27',['macOS .app bundle — FIX',['../md_docs_2AUDIT.html#autotoc_md25',1,'']]],
  ['by_20the_20current_20fork_20relative_20to_20naylacruz_20522bc3a_28',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md119',1,'']]],
  ['by_20this_20fork_29',['4.2 Releases produced by this fork',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md114',1,'']]]
];
