var searchData=
[
  ['tag_20push_0',['8.3 Release flow (what happens on a &lt;span class=&quot;tt&quot;&gt;v*&lt;/span&gt; tag push)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md148',1,'']]],
  ['tag_20reference_20integrity_1',['45. Git/tag/reference integrity',['../md_docs_2TASKS.html#autotoc_md263',1,'']]],
  ['taken_20with_20the_20alternatives_20considered_2',['7. Decisions Taken (with the alternatives considered)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md128',1,'']]],
  ['tar_20gz_20—_20keep_20harden_3',['Linux tar.gz — KEEP / HARDEN',['../md_docs_2AUDIT.html#autotoc_md29',1,'']]],
  ['tar_20gz_20distribution_4',['P0 — Linux DEB/RPM/tar.gz distribution',['../md_docs_2TASKS.html#autotoc_md216',1,'']]],
  ['tarball_20correctness_5',['18. Linux tarball correctness',['../md_docs_2TASKS.html#autotoc_md219',1,'']]],
  ['target_20architecture_6',['Target architecture',['../md_docs_2AUDIT.html#autotoc_md40',1,'']]],
  ['target_20classification_7',['Target classification',['../md_docs_2AUDIT.html#autotoc_md90',1,'']]],
  ['target_20install_20definitions_8',['Target/install definitions',['../md_docs_2AUDIT.html#autotoc_md9',1,'']]],
  ['target_20matrix_9',['6. Current vs target matrix',['../md_docs_2AUDIT.html#autotoc_md16',1,'']]],
  ['target_20repo_20dispatches_202026_2009_2025_10',['Live acceptance evidence (target-repo dispatches, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md323',1,'']]],
  ['task_20plan_11',['CPP Project Template — Distribution Hardening Task Plan',['../md_docs_2TASKS.html',1,'']]],
  ['team_20evidence_20note_12',['13.8 Team / evidence note',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md175',1,'']]],
  ['template_13',['C++ Project Template',['../index.html',1,'']]],
  ['template_14',['template',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md106',1,'3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md112',1,'4. The Intermediate Fork: &lt;span class=&quot;tt&quot;&gt;NaylaCruz/cpp-project-template&lt;/span&gt;'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md117',1,'5. The Current Fork: &lt;span class=&quot;tt&quot;&gt;Jackie-SDX/cpp-project-template&lt;/span&gt;']]],
  ['template_20—_20distribution_20hardening_20task_20plan_15',['CPP Project Template — Distribution Hardening Task Plan',['../md_docs_2TASKS.html',1,'']]],
  ['template_20—_20engineering_20documentation_16',['C++ Project Template — Engineering Documentation',['../md_docs_2PROJECT__DOCUMENTATION.html',1,'']]],
  ['term_20maintenance_17',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md256',1,'']]],
  ['test_20manual_20install_20not_20recommended_20prefer_20vcpkg_18',['Google Test (manual install not recommended, prefer vcpkg)',['../md_docs_2install.html#autotoc_md338',1,'']]],
  ['testing_19',['Testing',['../md_docs_2development__guide.html#autotoc_md278',1,'Testing'],['../md_docs_2development__guide.html#autotoc_md297',1,'Testing']]],
  ['testing_20of_20the_20release_20path_20',['47. Security testing of the release path',['../md_docs_2TASKS.html#autotoc_md265',1,'']]],
  ['the_20alternatives_20considered_21',['7. Decisions Taken (with the alternatives considered)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md128',1,'']]],
  ['the_20architecture_20names_20the_20best_20i686_20x86_5f64_20arm64_22',['11.2 Q: Are the architecture names the best? (i686, x86_64, arm64)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md157',1,'']]],
  ['the_20best_20i686_20x86_5f64_20arm64_23',['11.2 Q: Are the architecture names the best? (i686, x86_64, arm64)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md157',1,'']]],
  ['the_20current_20fork_20relative_20to_20naylacruz_20522bc3a_24',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md119',1,'']]],
  ['the_20current_20fork_3a_20jackie_20sdx_20cpp_20project_20template_25',['5. The Current Fork: &lt;span class=&quot;tt&quot;&gt;Jackie-SDX/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md117',1,'']]],
  ['the_20difference_20between_20clang_20and_20llvm_20in_20the_20matrix_26',['11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'']]],
  ['the_20divergent_20github_20gitlab_20copies_20into_20one_20repo_27',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md129',1,'']]],
  ['the_20durable_20core_28',['4.1 What NaylaCruz&apos;s pass introduced (the durable core)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md113',1,'']]],
  ['the_20final_20omission_20pass_29',['P1 — Additional cross-cutting controls from the final omission pass',['../md_docs_2TASKS.html#autotoc_md261',1,'']]],
  ['the_20intermediate_20fork_3a_20naylacruz_20cpp_20project_20template_30',['4. The Intermediate Fork: &lt;span class=&quot;tt&quot;&gt;NaylaCruz/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md112',1,'']]],
  ['the_20matrix_31',['11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'']]],
  ['the_20original_32',['the original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md109',1,'3.3 Engineering characteristics of the original'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md110',1,'3.4 Known limitations of the original']]],
  ['the_20original_20repo_3a_20mangad_20cpp_20project_20template_33',['3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md106',1,'']]],
  ['the_20project_20works_20now_20operational_20view_34',['8. How the Project Works Now (Operational View)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md145',1,'']]],
  ['the_20release_20path_35',['47. Security testing of the release path',['../md_docs_2TASKS.html#autotoc_md265',1,'']]],
  ['the_20repo_20itself_36',['7.15 D15 — OpenCode automations on the repo itself',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md143',1,'']]],
  ['the_20single_20source_20of_20build_20truth_20adr_20001_37',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['the_20wrong_20repository_20identity_38',['High: Windows release cache gate is keyed to the wrong repository identity',['../md_docs_2AUDIT.html#autotoc_md76',1,'']]],
  ['there_20benefits_20to_20compiling_20across_20all_20these_20compiler_20variants_39',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['these_20compiler_20variants_40',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['third_20party_20actions_20to_20commit_20shas_20adr_20003_41',['7.6 D6 — Pin third-party actions to commit SHAs (&lt;span class=&quot;tt&quot;&gt;ADR 003&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md134',1,'']]],
  ['third_20party_20compliance_42',['37. License and third-party compliance',['../md_docs_2TASKS.html#autotoc_md252',1,'']]],
  ['third_20party_20libraries_43',['Third-Party Libraries',['../index.html#autotoc_md364',1,'']]],
  ['this_20document_44',['14. Verification Ledger (evidence cited in this document)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md177',1,'']]],
  ['this_20fork_45',['4.2 Releases produced by this fork',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md114',1,'']]],
  ['this_20head_20before_20editing_46',['Findings (re-proven from this HEAD before editing)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md320',1,'']]],
  ['tips_47',['tips',['../md_docs_2development__guide.html#autotoc_md286',1,'CMake tips'],['../md_docs_2development__guide.html#autotoc_md287',1,'Doxygen tips'],['../md_docs_2development__guide.html#autotoc_md290',1,'GitHub Actions tips'],['../md_docs_2development__guide.html#autotoc_md292',1,'GitLab tips']]],
  ['to_20commit_20shas_20adr_20003_48',['7.6 D6 — Pin third-party actions to commit SHAs (&lt;span class=&quot;tt&quot;&gt;ADR 003&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md134',1,'']]],
  ['to_20compiling_20across_20all_20these_20compiler_20variants_49',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['to_20naylacruz_20522bc3a_50',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md119',1,'']]],
  ['to_20the_20wrong_20repository_20identity_51',['High: Windows release cache gate is keyed to the wrong repository identity',['../md_docs_2AUDIT.html#autotoc_md76',1,'']]],
  ['too_20late_52',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['toolchain_20integrity_53',['26. Dependency and toolchain integrity',['../md_docs_2TASKS.html#autotoc_md235',1,'']]],
  ['toolkit_54',['46. Consumer verification toolkit',['../md_docs_2TASKS.html#autotoc_md264',1,'']]],
  ['tracked_20snapshot_20verification_55',['21A. Round 3 — complete tracked-snapshot verification',['../md_docs_2AUDIT.html#autotoc_md72',1,'']]],
  ['trade_20offs_20visible_20from_20history_56',['4.3 Trade-offs visible from history',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md115',1,'']]],
  ['trail_57',['40. Release evidence and audit trail',['../md_docs_2TASKS.html#autotoc_md257',1,'']]],
  ['trust_20boundaries_58',['44. Build isolation and trust boundaries',['../md_docs_2TASKS.html#autotoc_md262',1,'']]],
  ['trust_20chain_59',['trust chain',['../md_docs_2TASKS.html#autotoc_md205',1,'8. Authenticode and trust chain'],['../md_docs_2AUDIT.html#autotoc_md48',1,'Recommended trust chain']]],
  ['trust_20model_60',['23. Recommended release trust model',['../md_docs_2AUDIT.html#autotoc_md87',1,'']]],
  ['truth_20adr_20001_61',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['tutorial_20links_62',['Tutorial links',['../md_docs_2development__guide.html#autotoc_md294',1,'']]],
  ['txt_63',['txt',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md174',1,'13.7 Residual follow-ups (carried over from &lt;span class=&quot;tt&quot;&gt;BUGS.txt&lt;/span&gt;)'],['../md_docs_2AUDIT.html#autotoc_md57',1,'CMakeLists.txt'],['../md_docs_2AUDIT.html#autotoc_md56',1,'src/projectwx/src/CMakeLists.txt']]]
];
