var searchData=
[
  ['objective_0',['13.1 Objective',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md168',1,'']]],
  ['observations_20found_20during_20inspection_1',['13.4 Bugs and observations found during inspection',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md171',1,'']]],
  ['occurs_20too_20late_2',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['of_20build_20truth_20adr_20001_3',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['of_20decisions_4',['12.1 Summary of decisions',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md161',1,'']]],
  ['of_20done_5',['Definition of done',['../md_docs_2TASKS.html#autotoc_md193',1,'']]],
  ['of_20release_20workflows_20adr_20005_20ci_20yml_6',['7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md130',1,'']]],
  ['of_20scope_20unless_20separately_20justified_7',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md271',1,'']]],
  ['of_20the_20original_8',['of the original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md109',1,'3.3 Engineering characteristics of the original'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md110',1,'3.4 Known limitations of the original']]],
  ['of_20the_20release_20path_9',['47. Security testing of the release path',['../md_docs_2TASKS.html#autotoc_md265',1,'']]],
  ['of_20upstream_20submission_10',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md139',1,'']]],
  ['offline_20and_20restricted_20network_20behavior_11',['34. Offline and restricted-network behavior',['../md_docs_2TASKS.html#autotoc_md247',1,'']]],
  ['offs_20visible_20from_20history_12',['4.3 Trade-offs visible from history',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md115',1,'']]],
  ['omission_20pass_13',['P1 — Additional cross-cutting controls from the final omission pass',['../md_docs_2TASKS.html#autotoc_md261',1,'']]],
  ['on_20a_20v_20tag_20push_14',['8.3 Release flow (what happens on a &lt;span class=&quot;tt&quot;&gt;v*&lt;/span&gt; tag push)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md148',1,'']]],
  ['on_20main_2096240c0_15',['5.1 State on &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md118',1,'']]],
  ['on_20the_20repo_20itself_16',['7.15 D15 — OpenCode automations on the repo itself',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md143',1,'']]],
  ['on_20windows_17',['on Windows',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md162',1,'12.2 Static vs. dynamic CRT on Windows'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md138',1,'7.10 D10 — Static vs dynamic CRT on Windows']]],
  ['one_20release_20manifest_20for_20github_20and_20gitlab_18',['3. One release manifest for GitHub and GitLab',['../md_docs_2TASKS.html#autotoc_md198',1,'']]],
  ['one_20repo_19',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md129',1,'']]],
  ['only_20',['Windows .7z — REMOVE FROM PUBLISHING / KEEP DISABLED HISTORICAL BLOCK ONLY',['../md_docs_2AUDIT.html#autotoc_md21',1,'']]],
  ['open_20risks_21',['20. Open risks',['../md_docs_2AUDIT.html#autotoc_md63',1,'']]],
  ['opencode_20automations_20on_20the_20repo_20itself_22',['7.15 D15 — OpenCode automations on the repo itself',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md143',1,'']]],
  ['operational_20maturity_20and_20long_20term_20maintenance_23',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md256',1,'']]],
  ['operational_20view_24',['8. How the Project Works Now (Operational View)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md145',1,'']]],
  ['operator_20action_3a_20cache_20budget_25',['16.4 Operator action: cache budget',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md185',1,'']]],
  ['opt_20in_20cdash_20instead_20of_20upstream_20submission_26',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md139',1,'']]],
  ['original_27',['original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md109',1,'3.3 Engineering characteristics of the original'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md110',1,'3.4 Known limitations of the original']]],
  ['original_2071cae18_20→_20current_2096240c0_28',['6.1 File inventory delta (original &lt;span class=&quot;tt&quot;&gt;71cae18&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md122',1,'']]],
  ['original_20repo_3a_20mangad_20cpp_20project_20template_29',['3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md106',1,'']]],
  ['original_20vs_20current_30',['6. Comparative Deep-Dive: Original vs Current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md121',1,'']]],
  ['original_20vs_20current_31',['6.3 Workflow inventory: original vs current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md124',1,'']]],
  ['out_32',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['out_20of_20scope_20unless_20separately_20justified_33',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md271',1,'']]],
  ['output_34',['Validation results (commands → output)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md316',1,'']]],
  ['over_20from_20bugs_20txt_35',['13.7 Residual follow-ups (carried over from &lt;span class=&quot;tt&quot;&gt;BUGS.txt&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md174',1,'']]],
  ['over_20from_20gitlab_20as_20is_36',['12.4 Carried over from GitLab as-is',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md164',1,'']]],
  ['overwrite_37',['Finding: release asset overwrite',['../md_docs_2AUDIT.html#autotoc_md37',1,'']]],
  ['owned_20by_20the_20current_20fork_20relative_20to_20naylacruz_20522bc3a_38',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md119',1,'']]]
];
