var searchData=
[
  ['s_20pass_20introduced_20the_20durable_20core_0',['4.1 What NaylaCruz&apos;s pass introduced (the durable core)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md113',1,'']]],
  ['sanitizers_1',['Sanitizers',['../md_docs_2development__guide.html#autotoc_md284',1,'']]],
  ['sbom_2',['27. SBOM',['../md_docs_2TASKS.html#autotoc_md236',1,'']]],
  ['sbom_20provenance_3',['SBOM/provenance',['../md_docs_2AUDIT.html#autotoc_md47',1,'']]],
  ['sbom_20provenance_20attestations_20and_20supply_20chain_20controls_4',['P1 — SBOM, provenance, attestations, and supply-chain controls',['../md_docs_2TASKS.html#autotoc_md234',1,'']]],
  ['scope_20and_20hard_20stop_20conditions_5',['1. Scope and hard-stop conditions',['../md_docs_2AUDIT.html#autotoc_md1',1,'']]],
  ['scope_20unless_20separately_20justified_6',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md271',1,'']]],
  ['sdx_20cpp_20project_20template_7',['5. The Current Fork: &lt;span class=&quot;tt&quot;&gt;Jackie-SDX/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md117',1,'']]],
  ['security_8',['31. GitLab parity and security',['../md_docs_2TASKS.html#autotoc_md242',1,'']]],
  ['security_20advisory_20and_20vex_20handling_9',['49. Security advisory and VEX handling',['../md_docs_2TASKS.html#autotoc_md267',1,'']]],
  ['security_20and_20governance_10',['P1 — CI/CD security and governance',['../md_docs_2TASKS.html#autotoc_md240',1,'']]],
  ['security_20assessment_11',['14. Supply-chain and security assessment',['../md_docs_2AUDIT.html#autotoc_md41',1,'']]],
  ['security_20support_20policy_12',['38. Security/support policy',['../md_docs_2TASKS.html#autotoc_md253',1,'']]],
  ['security_20testing_20of_20the_20release_20path_13',['47. Security testing of the release path',['../md_docs_2TASKS.html#autotoc_md265',1,'']]],
  ['semantics_14',['7. Release-critical CI failure semantics',['../md_docs_2TASKS.html#autotoc_md202',1,'']]],
  ['separately_20justified_15',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md271',1,'']]],
  ['separation_20of_20release_20workflows_20adr_20005_20ci_20yml_16',['7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md130',1,'']]],
  ['session_20record_202026_2009_2023_17',['13. Release Archive Policy — Session Record (2026-09-23)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md167',1,'']]],
  ['shas_20adr_20003_18',['7.6 D6 — Pin third-party actions to commit SHAs (&lt;span class=&quot;tt&quot;&gt;ADR 003&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md134',1,'']]],
  ['signing_19',['Signing',['../md_docs_2development__guide.html#autotoc_md304',1,'']]],
  ['signing_20key_20management_20',['29. Signing-key management',['../md_docs_2TASKS.html#autotoc_md238',1,'']]],
  ['single_20release_20identity_20and_20version_20contract_21',['1. Single release identity and version contract',['../md_docs_2TASKS.html#autotoc_md196',1,'']]],
  ['single_20source_20of_20build_20truth_20adr_20001_22',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['single_20version_20resolution_20anchor_23',['7.12 D12 — Single version resolution anchor',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md140',1,'']]],
  ['smoke_20yml_24',['smoke yml',['../md_docs_2AUDIT.html#autotoc_md59',1,'.github/workflows/windows-arm64-package-smoke.yml'],['../md_docs_2AUDIT.html#autotoc_md58',1,'.github/workflows/windows-package-smoke.yml']]],
  ['snapshot_25',['Exact repository snapshot',['../md_docs_2AUDIT.html#autotoc_md73',1,'']]],
  ['snapshot_20verification_26',['21A. Round 3 — complete tracked-snapshot verification',['../md_docs_2AUDIT.html#autotoc_md72',1,'']]],
  ['source_20configuration_27',['Medium: package metadata identity is duplicated in source configuration',['../md_docs_2AUDIT.html#autotoc_md78',1,'']]],
  ['source_20integrity_28',['Source/integrity',['../md_docs_2AUDIT.html#autotoc_md14',1,'']]],
  ['source_20level_20changes_20worth_20calling_20out_29',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['source_20level_20findings_30',['Round 3 source-level findings',['../md_docs_2AUDIT.html#autotoc_md74',1,'']]],
  ['source_20of_20build_20truth_20adr_20001_31',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['src_20cmakelists_20txt_32',['src/projectwx/src/CMakeLists.txt',['../md_docs_2AUDIT.html#autotoc_md56',1,'']]],
  ['src_20projectwx_20src_20cmakelists_20txt_33',['src/projectwx/src/CMakeLists.txt',['../md_docs_2AUDIT.html#autotoc_md56',1,'']]],
  ['staging_20lane_34',['7.14 D14 — Experimental staging lane',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md142',1,'']]],
  ['stale_20release_20workflow_20inventory_20comment_35',['Medium: stale release-workflow inventory comment',['../md_docs_2AUDIT.html#autotoc_md77',1,'']]],
  ['standalone_20archives_36',['Standalone archives',['../md_docs_2AUDIT.html#autotoc_md86',1,'']]],
  ['started_37',['Started',['../md_docs_2getting__started.html',1,'Getting Started'],['../index.html#autotoc_md360',1,'Getting Started']]],
  ['state_20on_20main_2096240c0_38',['5.1 State on &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md118',1,'']]],
  ['statement_39',['26. Final audit statement',['../md_docs_2AUDIT.html#autotoc_md99',1,'']]],
  ['static_20analysis_40',['Static analysis',['../md_docs_2development__guide.html#autotoc_md277',1,'']]],
  ['static_20validation_41',['Repository/static validation',['../md_docs_2AUDIT.html#autotoc_md65',1,'']]],
  ['static_20vs_20dynamic_20crt_20on_20windows_42',['Static vs dynamic CRT on Windows',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md162',1,'12.2 Static vs. dynamic CRT on Windows'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md138',1,'7.10 D10 — Static vs dynamic CRT on Windows']]],
  ['status_43',['Progress status',['../index.html#autotoc_md358',1,'']]],
  ['still_20does_20not_20prove_44',['What Round 2 still does not prove',['../md_docs_2AUDIT.html#autotoc_md71',1,'']]],
  ['still_20runner_20credential_20dependent_20cannot_20be_20claimed_20green_20yet_45',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md317',1,'']]],
  ['stop_20conditions_46',['1. Scope and hard-stop conditions',['../md_docs_2AUDIT.html#autotoc_md1',1,'']]],
  ['strategy_47',['42. Update and distribution strategy',['../md_docs_2TASKS.html#autotoc_md259',1,'']]],
  ['strength_48',['Strength',['../md_docs_2AUDIT.html#autotoc_md32',1,'']]],
  ['strict_20separation_20of_20release_20workflows_20adr_20005_20ci_20yml_49',['7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md130',1,'']]],
  ['structural_20validation_50',['21. Artifact structural validation',['../md_docs_2TASKS.html#autotoc_md226',1,'']]],
  ['submission_51',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md139',1,'']]],
  ['summary_52',['1. Executive Summary',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['summary_20of_20decisions_53',['12.1 Summary of decisions',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md161',1,'']]],
  ['supply_20chain_20and_20security_20assessment_54',['14. Supply-chain and security assessment',['../md_docs_2AUDIT.html#autotoc_md41',1,'']]],
  ['supply_20chain_20controls_55',['P1 — SBOM, provenance, attestations, and supply-chain controls',['../md_docs_2TASKS.html#autotoc_md234',1,'']]],
  ['support_20policy_56',['38. Security/support policy',['../md_docs_2TASKS.html#autotoc_md253',1,'']]],
  ['support_20readiness_57',['P1 — Documentation, legal, and support readiness',['../md_docs_2TASKS.html#autotoc_md250',1,'']]],
  ['system_58',['system',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md146',1,'8.1 Build system'],['../md_docs_2AUDIT.html#autotoc_md5',1,'Build system']]]
];
