var searchData=
[
  ['c_0',['C++',['../md_docs_2development__guide.html#autotoc_md295',1,'']]],
  ['c_20project_20template_1',['C++ Project Template',['../index.html',1,'']]],
  ['c_20project_20template_20—_20engineering_20documentation_2',['C++ Project Template — Engineering Documentation',['../md_docs_2PROJECT__DOCUMENTATION.html',1,'']]],
  ['cache_20and_20release_20publication_20repair_202026_2009_2025_3',['16. CI cache and release publication repair (2026-09-25)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md181',1,'']]],
  ['cache_20budget_4',['16.4 Operator action: cache budget',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md185',1,'']]],
  ['cache_20contract_20adr_20006_202026_2009_2025_5',['PASS 4 — vcpkg binary-cache contract (ADR 006, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md319',1,'']]],
  ['cache_20correctness_6',['4. Release cache correctness',['../md_docs_2TASKS.html#autotoc_md199',1,'']]],
  ['cache_20gate_20is_20keyed_20to_20the_20wrong_20repository_20identity_7',['High: Windows release cache gate is keyed to the wrong repository identity',['../md_docs_2AUDIT.html#autotoc_md76',1,'']]],
  ['cache_20keys_20adr_20002_8',['7.5 D5 — Deterministic cache keys (&lt;span class=&quot;tt&quot;&gt;ADR 002&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md133',1,'']]],
  ['calling_20out_9',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['candidates_10',['10. Future Work (candidates)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md153',1,'']]],
  ['cannot_20be_20claimed_20green_20yet_11',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md317',1,'']]],
  ['carried_20over_20from_20bugs_20txt_12',['13.7 Residual follow-ups (carried over from &lt;span class=&quot;tt&quot;&gt;BUGS.txt&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md174',1,'']]],
  ['carried_20over_20from_20gitlab_20as_20is_13',['12.4 Carried over from GitLab as-is',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md164',1,'']]],
  ['causes_20and_20evidence_14',['16.2 Root causes and evidence',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md183',1,'']]],
  ['cd_20security_20and_20governance_15',['P1 — CI/CD security and governance',['../md_docs_2TASKS.html#autotoc_md240',1,'']]],
  ['cdash_16',['CDash',['../md_docs_2development__guide.html#autotoc_md285',1,'']]],
  ['cdash_20instead_20of_20upstream_20submission_17',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md139',1,'']]],
  ['centos_18',['RedHat / Fedora / CentOS',['../md_docs_2install.html#autotoc_md332',1,'']]],
  ['chain_19',['chain',['../md_docs_2TASKS.html#autotoc_md205',1,'8. Authenticode and trust chain'],['../md_docs_2AUDIT.html#autotoc_md48',1,'Recommended trust chain']]],
  ['chain_20and_20security_20assessment_20',['14. Supply-chain and security assessment',['../md_docs_2AUDIT.html#autotoc_md41',1,'']]],
  ['chain_20controls_21',['P1 — SBOM, provenance, attestations, and supply-chain controls',['../md_docs_2TASKS.html#autotoc_md234',1,'']]],
  ['changed_22',['changed',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md165',1,'12.5 Pre-existing items intentionally not changed'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md172',1,'13.5 Files changed']]],
  ['changes_20deliberately_20not_20advised_23',['19. Changes deliberately NOT advised',['../md_docs_2AUDIT.html#autotoc_md62',1,'']]],
  ['changes_20made_24',['16.3 Changes made',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md184',1,'']]],
  ['changes_20owned_20by_20the_20current_20fork_20relative_20to_20naylacruz_20522bc3a_25',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md119',1,'']]],
  ['changes_20proposed_26',['18. Exact future changes proposed',['../md_docs_2AUDIT.html#autotoc_md52',1,'']]],
  ['changes_20worth_20calling_20out_27',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['characteristics_20of_20the_20original_28',['3.3 Engineering characteristics of the original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md109',1,'']]],
  ['checklist_29',['Release gate — final acceptance checklist',['../md_docs_2TASKS.html#autotoc_md269',1,'']]],
  ['checks_30',['20. Binary-hardening checks',['../md_docs_2TASKS.html#autotoc_md223',1,'']]],
  ['ci_20cache_20and_20release_20publication_20repair_202026_2009_2025_31',['16. CI cache and release publication repair (2026-09-25)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md181',1,'']]],
  ['ci_20cd_20security_20and_20governance_32',['P1 — CI/CD security and governance',['../md_docs_2TASKS.html#autotoc_md240',1,'']]],
  ['ci_20failure_20semantics_33',['7. Release-critical CI failure semantics',['../md_docs_2TASKS.html#autotoc_md202',1,'']]],
  ['ci_20yml_34',['ci yml',['../md_docs_2AUDIT.html#autotoc_md54',1,'.gitlab/.gitlab-ci.yml'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md130',1,'7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)']]],
  ['cited_20in_20this_20document_35',['14. Verification Ledger (evidence cited in this document)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md177',1,'']]],
  ['claimed_20green_20yet_36',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md317',1,'']]],
  ['clang_37',['GCC / Clang',['../md_docs_2development__guide.html#autotoc_md280',1,'']]],
  ['clang_20and_20llvm_20in_20the_20matrix_38',['11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'']]],
  ['classification_39',['classification',['../md_docs_2AUDIT.html#autotoc_md89',1,'Current classification'],['../md_docs_2AUDIT.html#autotoc_md90',1,'Target classification']]],
  ['closure_40',['closure',['../md_docs_2TASKS.html#autotoc_md212',1,'13. macOS architecture and runtime closure'],['../md_docs_2TASKS.html#autotoc_md222',1,'19. Runtime dependency closure']]],
  ['cmake_41',['CMake',['../md_docs_2development__guide.html#autotoc_md296',1,'']]],
  ['cmake_42',['cmake',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md163',1,'12.3 &lt;span class=&quot;tt&quot;&gt;cmake/cpack_module.cmake&lt;/span&gt;'],['../md_docs_2AUDIT.html#autotoc_md55',1,'cmake/cpack_module.cmake']]],
  ['cmake_20cpack_43',['CMake / CPack',['../md_docs_2AUDIT.html#autotoc_md94',1,'']]],
  ['cmake_20cpack_5fmodule_20cmake_44',['cmake cpack_module cmake',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md163',1,'12.3 &lt;span class=&quot;tt&quot;&gt;cmake/cpack_module.cmake&lt;/span&gt;'],['../md_docs_2AUDIT.html#autotoc_md55',1,'cmake/cpack_module.cmake']]],
  ['cmake_20d9_20rationale_45',['7.9 D9 — Dual package manager, vcpkg default (&lt;span class=&quot;tt&quot;&gt;PackageManager.cmake&lt;/span&gt; + D9 rationale)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md137',1,'']]],
  ['cmake_20tips_46',['CMake tips',['../md_docs_2development__guide.html#autotoc_md286',1,'']]],
  ['cmakelists_20txt_47',['CMakeLists txt',['../md_docs_2AUDIT.html#autotoc_md57',1,'CMakeLists.txt'],['../md_docs_2AUDIT.html#autotoc_md56',1,'src/projectwx/src/CMakeLists.txt']]],
  ['cmakepresets_20as_20the_20single_20source_20of_20build_20truth_20adr_20001_48',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['commands_20→_20actual_20result_49',['Validation (commands → actual result)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md322',1,'']]],
  ['commands_20→_20output_50',['Validation results (commands → output)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md316',1,'']]],
  ['comment_51',['Medium: stale release-workflow inventory comment',['../md_docs_2AUDIT.html#autotoc_md77',1,'']]],
  ['commit_20shas_20adr_20003_52',['7.6 D6 — Pin third-party actions to commit SHAs (&lt;span class=&quot;tt&quot;&gt;ADR 003&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md134',1,'']]],
  ['comparative_20deep_20dive_3a_20original_20vs_20current_53',['6. Comparative Deep-Dive: Original vs Current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md121',1,'']]],
  ['compatibility_20and_20platform_20baselines_54',['P0 — Runtime compatibility and platform baselines',['../md_docs_2TASKS.html#autotoc_md221',1,'']]],
  ['compile_55',['Compile',['../md_docs_2install.html#autotoc_md341',1,'']]],
  ['compiler_20architecture_20q_20a_202026_2009_2023_56',['11. Compiler &amp;amp; Architecture Q&amp;amp;A (2026-09-23)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md155',1,'']]],
  ['compiler_20variants_57',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['compiling_20across_20all_20these_20compiler_20variants_58',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['complete_20tracked_20snapshot_20verification_59',['21A. Round 3 — complete tracked-snapshot verification',['../md_docs_2AUDIT.html#autotoc_md72',1,'']]],
  ['compliance_60',['37. License and third-party compliance',['../md_docs_2TASKS.html#autotoc_md252',1,'']]],
  ['conclusions_61',['Round 3 unchanged conclusions',['../md_docs_2AUDIT.html#autotoc_md80',1,'']]],
  ['conditional_20localization_20accessibility_20readiness_62',['48. Conditional localization/accessibility readiness',['../md_docs_2TASKS.html#autotoc_md266',1,'']]],
  ['conditions_63',['1. Scope and hard-stop conditions',['../md_docs_2AUDIT.html#autotoc_md1',1,'']]],
  ['confidence_64',['2. Confidence',['../md_docs_2AUDIT.html#autotoc_md2',1,'']]],
  ['configuration_65',['Medium: package metadata identity is duplicated in source configuration',['../md_docs_2AUDIT.html#autotoc_md78',1,'']]],
  ['confirmed_20macos_20architecture_20gap_66',['Confirmed macOS architecture gap',['../md_docs_2AUDIT.html#autotoc_md79',1,'']]],
  ['considered_67',['7. Decisions Taken (with the alternatives considered)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md128',1,'']]],
  ['consumer_20verification_20toolkit_68',['46. Consumer verification toolkit',['../md_docs_2TASKS.html#autotoc_md264',1,'']]],
  ['contained_2082_20files_69',['3.2 What it contained (82 files)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md108',1,'']]],
  ['continuous_20verification_70',['43. Continuous verification',['../md_docs_2TASKS.html#autotoc_md260',1,'']]],
  ['contract_71',['contract',['../md_docs_2TASKS.html#autotoc_md196',1,'1. Single release identity and version contract'],['../md_docs_2AUDIT.html#autotoc_md61',1,'New release manifest/evidence contract']]],
  ['contract_20adr_20006_202026_2009_2025_72',['PASS 4 — vcpkg binary-cache contract (ADR 006, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md319',1,'']]],
  ['contract_20live_20v0_200_209_73',['Baseline release contract (live, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md311',1,'']]],
  ['controls_74',['controls',['../md_docs_2TASKS.html#autotoc_md234',1,'P1 — SBOM, provenance, attestations, and supply-chain controls'],['../md_docs_2AUDIT.html#autotoc_md42',1,'Positive controls']]],
  ['controls_20from_20the_20final_20omission_20pass_75',['P1 — Additional cross-cutting controls from the final omission pass',['../md_docs_2TASKS.html#autotoc_md261',1,'']]],
  ['copies_20into_20one_20repo_76',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md129',1,'']]],
  ['copy_77',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md160',1,'']]],
  ['copy_20gitlab_20copy_78',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md160',1,'']]],
  ['core_79',['4.1 What NaylaCruz&apos;s pass introduced (the durable core)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md113',1,'']]],
  ['correct_20product_20repository_20identity_80',['2. Correct product/repository identity',['../md_docs_2TASKS.html#autotoc_md197',1,'']]],
  ['correctness_81',['correctness',['../md_docs_2TASKS.html#autotoc_md217',1,'16. Debian package correctness'],['../md_docs_2TASKS.html#autotoc_md218',1,'17. RPM package correctness'],['../md_docs_2TASKS.html#autotoc_md219',1,'18. Linux tarball correctness'],['../md_docs_2TASKS.html#autotoc_md199',1,'4. Release cache correctness']]],
  ['coverage_82',['Coverage',['../md_docs_2development__guide.html#autotoc_md279',1,'Coverage'],['../md_docs_2development__guide.html#autotoc_md298',1,'Coverage']]],
  ['coverity_20adr_20004_83',['7.8 D8 — Manual Coverity (&lt;span class=&quot;tt&quot;&gt;ADR 004&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md136',1,'']]],
  ['cpack_84',['CMake / CPack',['../md_docs_2AUDIT.html#autotoc_md94',1,'']]],
  ['cpack_5fmodule_20cmake_85',['cpack_module cmake',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md163',1,'12.3 &lt;span class=&quot;tt&quot;&gt;cmake/cpack_module.cmake&lt;/span&gt;'],['../md_docs_2AUDIT.html#autotoc_md55',1,'cmake/cpack_module.cmake']]],
  ['cpp_20project_20template_86',['cpp project template',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md106',1,'3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md112',1,'4. The Intermediate Fork: &lt;span class=&quot;tt&quot;&gt;NaylaCruz/cpp-project-template&lt;/span&gt;'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md117',1,'5. The Current Fork: &lt;span class=&quot;tt&quot;&gt;Jackie-SDX/cpp-project-template&lt;/span&gt;']]],
  ['cpp_20project_20template_20—_20distribution_20hardening_20task_20plan_87',['CPP Project Template — Distribution Hardening Task Plan',['../md_docs_2TASKS.html',1,'']]],
  ['credential_20dependent_20cannot_20be_20claimed_20green_20yet_88',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md317',1,'']]],
  ['critical_20ci_20failure_20semantics_89',['7. Release-critical CI failure semantics',['../md_docs_2TASKS.html#autotoc_md202',1,'']]],
  ['critical_3a_20github_20release_20version_20resolution_20occurs_20too_20late_90',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['cross_20cutting_20controls_20from_20the_20final_20omission_20pass_91',['P1 — Additional cross-cutting controls from the final omission pass',['../md_docs_2TASKS.html#autotoc_md261',1,'']]],
  ['cross_20platform_20lifecycle_20matrix_92',['33. Cross-platform lifecycle matrix',['../md_docs_2TASKS.html#autotoc_md246',1,'']]],
  ['cross_20platform_20matrix_20findings_93',['11. Cross-platform matrix findings',['../md_docs_2AUDIT.html#autotoc_md31',1,'']]],
  ['crt_20on_20windows_94',['CRT on Windows',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md162',1,'12.2 Static vs. dynamic CRT on Windows'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md138',1,'7.10 D10 — Static vs dynamic CRT on Windows']]],
  ['current_95',['6. Comparative Deep-Dive: Original vs Current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md121',1,'']]],
  ['current_96',['6.3 Workflow inventory: original vs current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md124',1,'']]],
  ['current_2096240c0_97',['6.1 File inventory delta (original &lt;span class=&quot;tt&quot;&gt;71cae18&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md122',1,'']]],
  ['current_20classification_98',['Current classification',['../md_docs_2AUDIT.html#autotoc_md89',1,'']]],
  ['current_20distribution_20inventory_20—_20v0_200_209_99',['5. Current distribution inventory — v0.0.9',['../md_docs_2AUDIT.html#autotoc_md10',1,'']]],
  ['current_20fork_20relative_20to_20naylacruz_20522bc3a_100',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md119',1,'']]],
  ['current_20fork_3a_20jackie_20sdx_20cpp_20project_20template_101',['5. The Current Fork: &lt;span class=&quot;tt&quot;&gt;Jackie-SDX/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md117',1,'']]],
  ['current_20v0_200_204_102',['6.4 Release asset delta (MangaD &lt;span class=&quot;tt&quot;&gt;v0.0.1&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;v0.0.4&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md125',1,'']]],
  ['current_20v0_200_209_103',['13.2 New policy (current, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md169',1,'']]],
  ['current_20vs_20target_20matrix_104',['6. Current vs target matrix',['../md_docs_2AUDIT.html#autotoc_md16',1,'']]],
  ['custom_20docker_20images_105',['Custom Docker images',['../md_docs_2development__guide.html#autotoc_md293',1,'']]],
  ['cut_20procedure_106',['16.5 Release re-cut procedure',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md186',1,'']]],
  ['cutting_20controls_20from_20the_20final_20omission_20pass_107',['P1 — Additional cross-cutting controls from the final omission pass',['../md_docs_2TASKS.html#autotoc_md261',1,'']]]
];
