var searchData=
[
  ['mac_0',['Linux &amp;amp; Mac',['../md_docs_2install.html#autotoc_md342',1,'']]],
  ['macos_1',['MacOS',['../md_docs_2install.html#autotoc_md352',1,'']]],
  ['macos_2',['macOS',['../md_docs_2AUDIT.html#autotoc_md45',1,'macOS'],['../md_docs_2AUDIT.html#autotoc_md83',1,'macOS'],['../md_docs_2install.html#autotoc_md340',1,'macOS']]],
  ['macos_20app_20bundle_20—_20fix_3',['macOS .app bundle — FIX',['../md_docs_2AUDIT.html#autotoc_md25',1,'']]],
  ['macos_20architecture_20and_20runtime_20closure_4',['13. macOS architecture and runtime closure',['../md_docs_2TASKS.html#autotoc_md212',1,'']]],
  ['macos_20architecture_20gap_5',['Confirmed macOS architecture gap',['../md_docs_2AUDIT.html#autotoc_md79',1,'']]],
  ['macos_20assessment_6',['8. macOS assessment',['../md_docs_2AUDIT.html#autotoc_md22',1,'']]],
  ['macos_20distribution_7',['P0 — macOS distribution',['../md_docs_2TASKS.html#autotoc_md210',1,'']]],
  ['macos_20distribution_20lifecycle_8',['15. macOS distribution lifecycle',['../md_docs_2TASKS.html#autotoc_md214',1,'']]],
  ['macos_20dmg_20—_20keep_20fix_9',['macOS DMG — KEEP / FIX',['../md_docs_2AUDIT.html#autotoc_md24',1,'']]],
  ['macos_20representative_20artifact_10',['macOS representative artifact',['../md_docs_2AUDIT.html#autotoc_md70',1,'']]],
  ['macos_20zip_20—_20keep_20fix_11',['macOS ZIP — KEEP / FIX',['../md_docs_2AUDIT.html#autotoc_md23',1,'']]],
  ['macos_3a_2012_20artifacts_12',['macOS: 12 artifacts',['../md_docs_2AUDIT.html#autotoc_md13',1,'']]],
  ['made_13',['16.3 Changes made',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md184',1,'']]],
  ['main_2096240c0_14',['5.1 State on &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md118',1,'']]],
  ['maintenance_15',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md256',1,'']]],
  ['management_16',['29. Signing-key management',['../md_docs_2TASKS.html#autotoc_md238',1,'']]],
  ['manager_20vcpkg_20default_20packagemanager_20cmake_20d9_20rationale_17',['7.9 D9 — Dual package manager, vcpkg default (&lt;span class=&quot;tt&quot;&gt;PackageManager.cmake&lt;/span&gt; + D9 rationale)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md137',1,'']]],
  ['mangad_20cpp_20project_20template_18',['3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md106',1,'']]],
  ['mangad_20v0_200_201_20→_20current_20v0_200_204_19',['6.4 Release asset delta (MangaD &lt;span class=&quot;tt&quot;&gt;v0.0.1&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;v0.0.4&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md125',1,'']]],
  ['manifest_20duplication_20',['Finding: manifest duplication',['../md_docs_2AUDIT.html#autotoc_md36',1,'']]],
  ['manifest_20evidence_20contract_21',['New release manifest/evidence contract',['../md_docs_2AUDIT.html#autotoc_md61',1,'']]],
  ['manifest_20for_20github_20and_20gitlab_22',['3. One release manifest for GitHub and GitLab',['../md_docs_2TASKS.html#autotoc_md198',1,'']]],
  ['manifests_20must_20never_20leak_20into_20uploads_23',['7.3 D3 — Release inventory manifests must never leak into uploads',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md131',1,'']]],
  ['manjaro_20linux_24',['Arch Linux / Manjaro Linux',['../md_docs_2install.html#autotoc_md330',1,'']]],
  ['manual_20coverity_20adr_20004_25',['7.8 D8 — Manual Coverity (&lt;span class=&quot;tt&quot;&gt;ADR 004&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md136',1,'']]],
  ['manual_20install_20not_20recommended_20prefer_20vcpkg_26',['manual install not recommended prefer vcpkg',['../md_docs_2install.html#autotoc_md338',1,'Google Test (manual install not recommended, prefer vcpkg)'],['../md_docs_2install.html#autotoc_md337',1,'wxWidgets (manual install not recommended, prefer vcpkg)']]],
  ['math_27',['13.3 Inventory math',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md170',1,'']]],
  ['matrix_28',['matrix',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?'],['../md_docs_2TASKS.html#autotoc_md246',1,'33. Cross-platform lifecycle matrix'],['../md_docs_2AUDIT.html#autotoc_md16',1,'6. Current vs target matrix']]],
  ['matrix_20findings_29',['11. Cross-platform matrix findings',['../md_docs_2AUDIT.html#autotoc_md31',1,'']]],
  ['matrix_20qa_30',['23. Full release-matrix QA',['../md_docs_2TASKS.html#autotoc_md228',1,'']]],
  ['maturity_20and_20long_20term_20maintenance_31',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md256',1,'']]],
  ['md_32',['docs/install.md',['../md_docs_2AUDIT.html#autotoc_md60',1,'']]],
  ['medium_3a_20package_20metadata_20identity_20is_20duplicated_20in_20source_20configuration_33',['Medium: package metadata identity is duplicated in source configuration',['../md_docs_2AUDIT.html#autotoc_md78',1,'']]],
  ['medium_3a_20stale_20release_20workflow_20inventory_20comment_34',['Medium: stale release-workflow inventory comment',['../md_docs_2AUDIT.html#autotoc_md77',1,'']]],
  ['merge_20notes_3a_20github_20copy_20gitlab_20copy_35',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md160',1,'']]],
  ['metadata_20identity_20is_20duplicated_20in_20source_20configuration_36',['Medium: package metadata identity is duplicated in source configuration',['../md_docs_2AUDIT.html#autotoc_md78',1,'']]],
  ['migration_37',['39. Release notes and migration',['../md_docs_2TASKS.html#autotoc_md254',1,'']]],
  ['mingw_38',['MinGW',['../md_docs_2install.html#autotoc_md335',1,'']]],
  ['mint_20ubuntu_39',['Debian / Linux Mint / Ubuntu',['../md_docs_2install.html#autotoc_md331',1,'']]],
  ['model_40',['23. Recommended release trust model',['../md_docs_2AUDIT.html#autotoc_md87',1,'']]],
  ['msi_20—_20keep_20harden_41',['Windows WiX/MSI — KEEP / HARDEN',['../md_docs_2AUDIT.html#autotoc_md20',1,'']]],
  ['msi_20lifecycle_42',['11. WiX MSI lifecycle',['../md_docs_2TASKS.html#autotoc_md208',1,'']]],
  ['msvc_43',['MSVC',['../md_docs_2development__guide.html#autotoc_md281',1,'MSVC'],['../md_docs_2install.html#autotoc_md334',1,'MSVC']]],
  ['must_20never_20leak_20into_20uploads_44',['7.3 D3 — Release inventory manifests must never leak into uploads',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md131',1,'']]],
  ['must_20not_20block_45',['Deferred (per issue §7, must not block)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md312',1,'']]]
];
