var searchData=
[
  ['lane_0',['7.14 D14 — Experimental staging lane',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md142',1,'']]],
  ['late_1',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['leak_20into_20uploads_2',['7.3 D3 — Release inventory manifests must never leak into uploads',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md131',1,'']]],
  ['ledger_3',['Distribution Hardening — Evidence Ledger',['../md_docs_2distribution-hardening-evidence.html',1,'']]],
  ['ledger_4',['16.9 Evidence ledger',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md190',1,'']]],
  ['ledger_20evidence_20cited_20in_20this_20document_5',['14. Verification Ledger (evidence cited in this document)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md177',1,'']]],
  ['legal_20and_20support_20readiness_6',['P1 — Documentation, legal, and support readiness',['../md_docs_2TASKS.html#autotoc_md250',1,'']]],
  ['level_20changes_20worth_20calling_20out_7',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['level_20findings_8',['Round 3 source-level findings',['../md_docs_2AUDIT.html#autotoc_md74',1,'']]],
  ['level_20validation_9',['Round 2 artifact-level validation',['../md_docs_2AUDIT.html#autotoc_md67',1,'']]],
  ['libraries_10',['Third-Party Libraries',['../index.html#autotoc_md364',1,'']]],
  ['libraries_11',['Adding libraries',['../md_docs_2development__guide.html#autotoc_md288',1,'']]],
  ['license_12',['License',['../index.html#autotoc_md363',1,'']]],
  ['license_20and_20third_20party_20compliance_13',['37. License and third-party compliance',['../md_docs_2TASKS.html#autotoc_md252',1,'']]],
  ['licenses_14',['Licenses',['../md_docs_2development__guide.html#autotoc_md303',1,'']]],
  ['lifecycle_15',['lifecycle',['../md_docs_2TASKS.html#autotoc_md207',1,'10. NSIS lifecycle'],['../md_docs_2TASKS.html#autotoc_md208',1,'11. WiX MSI lifecycle'],['../md_docs_2TASKS.html#autotoc_md214',1,'15. macOS distribution lifecycle']]],
  ['lifecycle_20and_20user_20experience_16',['P1 — Installer/package lifecycle and user experience',['../md_docs_2TASKS.html#autotoc_md245',1,'']]],
  ['lifecycle_20matrix_17',['33. Cross-platform lifecycle matrix',['../md_docs_2TASKS.html#autotoc_md246',1,'']]],
  ['limitations_18',['Research limitations',['../md_docs_2TASKS.html#autotoc_md274',1,'']]],
  ['limitations_20of_20the_20original_19',['3.4 Known limitations of the original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md110',1,'']]],
  ['limits_20',['16.8 Residual risks and honest limits',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md189',1,'']]],
  ['lineage_20and_20fork_20graph_21',['2. Repository Lineage and Fork Graph',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md104',1,'']]],
  ['links_22',['Tutorial links',['../md_docs_2development__guide.html#autotoc_md294',1,'']]],
  ['linux_23',['Linux',['../md_docs_2install.html#autotoc_md330',1,'Arch Linux / Manjaro Linux'],['../md_docs_2AUDIT.html#autotoc_md46',1,'Linux'],['../md_docs_2AUDIT.html#autotoc_md97',1,'Linux'],['../md_docs_2install.html#autotoc_md329',1,'Linux']]],
  ['linux_20assessment_24',['9. Linux assessment',['../md_docs_2AUDIT.html#autotoc_md26',1,'']]],
  ['linux_20deb_25',['Linux DEB',['../md_docs_2AUDIT.html#autotoc_md84',1,'']]],
  ['linux_20deb_20rpm_20tar_20gz_20distribution_26',['P0 — Linux DEB/RPM/tar.gz distribution',['../md_docs_2TASKS.html#autotoc_md216',1,'']]],
  ['linux_20mac_27',['Linux &amp;amp; Mac',['../md_docs_2install.html#autotoc_md342',1,'']]],
  ['linux_20manjaro_20linux_28',['Arch Linux / Manjaro Linux',['../md_docs_2install.html#autotoc_md330',1,'']]],
  ['linux_20mint_20ubuntu_29',['Debian / Linux Mint / Ubuntu',['../md_docs_2install.html#autotoc_md331',1,'']]],
  ['linux_20representative_20artifact_30',['Linux representative artifact',['../md_docs_2AUDIT.html#autotoc_md68',1,'']]],
  ['linux_20rpm_31',['Linux RPM',['../md_docs_2AUDIT.html#autotoc_md85',1,'']]],
  ['linux_20tar_20gz_20—_20keep_20harden_32',['Linux tar.gz — KEEP / HARDEN',['../md_docs_2AUDIT.html#autotoc_md29',1,'']]],
  ['linux_20tarball_20correctness_33',['18. Linux tarball correctness',['../md_docs_2TASKS.html#autotoc_md219',1,'']]],
  ['linux_3a_2015_20artifacts_34',['Linux: 15 artifacts',['../md_docs_2AUDIT.html#autotoc_md12',1,'']]],
  ['live_20acceptance_20evidence_20target_20repo_20dispatches_202026_2009_2025_35',['Live acceptance evidence (target-repo dispatches, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md323',1,'']]],
  ['live_20v0_200_209_36',['Baseline release contract (live, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md311',1,'']]],
  ['llvm_20in_20the_20matrix_37',['11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'']]],
  ['local_20validation_202026_2009_2025_38',['PASS 1-3 — Implementation and local validation (2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md314',1,'']]],
  ['localization_20accessibility_20readiness_39',['48. Conditional localization/accessibility readiness',['../md_docs_2TASKS.html#autotoc_md266',1,'']]],
  ['long_20term_20maintenance_40',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md256',1,'']]]
];
